name: Client Side Development
on:
    push:
        pull_request:
            branches: [main]

jobs:
    build:
        runs-on: self-hosted

        defaults:
            run:
                working-directory: ./client

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install packages
              working-directory: ./client
              run: |
                  npm install --global yarn
                  yarn
                  yarn build
